// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package v1

// CreateOrderItem defines model for CreateOrderItem.
type CreateOrderItem struct {
	// ProductID Unique identifier of the product
	ProductID string `json:"productID"`

	// Quantity Quantity of the product
	Quantity int `json:"quantity"`

	// UserID Unique identifier of the user
	UserID string `json:"userID"`
}

// CreateOrderRequest defines model for CreateOrderRequest.
type CreateOrderRequest struct {
	Data CreateOrderItem `json:"data"`
}

// ErrorItem defines model for ErrorItem.
type ErrorItem struct {
	// Detail A human-readable explanation specific to this occurrence of the problem
	Detail string `json:"detail"`

	// Id Identificator of a request
	Id     string       `json:"id"`
	Meta   ErrorMeta    `json:"meta"`
	Source *ErrorSource `json:"source,omitempty"`

	// Status The HTTP status code applicable to this problem, expressed as a string value
	Status string `json:"status"`
}

// ErrorMeta defines model for ErrorMeta.
type ErrorMeta struct {
	// Timestamp Timestamp of the occurrence of the problem in RFC3339 format
	Timestamp *string `json:"timestamp,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Errors []ErrorItem `json:"errors"`
}

// ErrorSource defines model for ErrorSource.
type ErrorSource struct {
	// Pointer a JSON Pointer [RFC6901] to the value in the request document that caused the error
	Pointer string `json:"pointer"`
}

// CreateOrderJSONRequestBody defines body for CreateOrder for application/json ContentType.
type CreateOrderJSONRequestBody = CreateOrderRequest
